export default [
	{
		repo: 'rob-3/steel-lang',
		description:
			'Steel is a passion project programming language with some interesting design choices like true pass-by-reference semantics and rational, arbitrary precision numbers by default.'
	},
	{
		repo: 'poop-team/daydream',
		description:
			'Social platform for sharing and creating AI images generated by Stable Diffusion '
	},
	{
		repo: 'knighthacks/scythe',
		description:
			'Scythe is a library that wraps and extends the Discord.js API to provide a simplified interface to create <a href="https://discord.com/developers/docs/interactions/application-commands">Discord slash commands</a>.'
	},
	{
		repo: 'knighthacks/hackathon-2021-frontend',
		description:
			'This site was used as the registration website for Knight Hacks 2021. It was built with React. An archived version currently lives at <a href="https://2021.knighthacks.org/">https://2021.knighthacks.org/</a>'
	},
	{
		repo: 'knighthacks/club-site-2021',
		description:
			'This site is the Knight Hacks student organization club site. It is built with React and Gatsby, and lives at <a href="https://knighthacks.org">https://knighthacks.org</a>.'
	},
	{
		repo: 'rob-3/website',
		description: 'The source code for this website!'
	}
];
